### ISSUE TITLE
A way to add release summaries

### ISSUE THREAD

**Issue by alexjfisher** [github-changelog-generator/github-changelog-generator#582]
Hi

It'd be really nice if there was a way to add release 'summaries' when using this tool. [Random example](https://github.com/puppetlabs/puppetlabs-stdlib/blob/8376c9b927d6034437db95126baa900a8213afcc/CHANGELOG.md#summary-1).

At first I thought the tool could either examine tags for annotations or maybe query the github 'release' data, but this won't work (people need to generate the changelog and include it in a release *before* they've tagged the project).

Maybe we could use a `.github-changelog-generator.yaml` (naming things is hard!) at the root of the repo?  I dunno... something along the lines of... (ill thought out example follows)
```yaml
---
releases:
  'v1.0.1':
    summary: 'This is a small bug fix release only affected Arch Linux users.'
  'v1.0.0':
    summary: 'This release adds support for internationalization.'
```

Any suggestions?
